### ISSUE TITLE
v4.5.1: chart requires kubeVersion: >=1.23.0-0 which is incompatible with Kubernetes v1.20.0

### ISSUE THREAD

**Issue by ctison** [pulumi/pulumi-kubernetes#2631]
### What happened?

When upgrading to [@pulumi/kubernetes@4.5.1](https://www.npmjs.com/package/@pulumi/kubernetes/v/4.5.1), the passed Kubernetes version seems to be stucked to `v1.20.0`, which makes failing Helm charts installation with Kubernetes version requirement.

### Example

```ts
new k8s.helm.v3.Release(
  'dragonfly',
  {
    chart: 'oci://ghcr.io/dragonflydb/dragonfly/helm/dragonfly',
    name: 'dragonfly',
    version: 'v1.11.0',
  },
  { parent: this },
);
```

```sh
$ pulumi up
[...]
Diagnostics:
  kubernetes:helm.sh/v3:Release (dragonfly):
    error: kubernetes:helm.sh/v3:Release resource 'dragonfly': property chart value {oci://ghcr.io/dragonflydb/dragonfly/helm/dragonfly} has a problem: chart requires kubeVersion: >=1.23.0-0 which is incompatible with Kubernetes v1.20.0; check the chart name and repository configuration.
```

### Output of `pulumi about`

CLI          
Version      3.90.1
Go Version   go1.21.3
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host     
OS       darwin
Version  14.0
Arch     arm64

### Additional context

Reverting to [@pulumi/kubernetes@4.4.0](https://www.npmjs.com/package/@pulumi/kubernetes/v/4.4.0) fixed my issue.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by bitofsky** [comment]
I'm also experiencing the same issue after upgrading to v4.5.1.
```
error: Error: invocation of kubernetes:helm:template returned an error: failed to generate YAML for specified Helm chart: failed to create chart from template: chart requires kubeVersion: >=1.21.0-0 which is incompatible with Kubernetes v1.20.0
```

**Comment by bitofsky** [comment]
Additional Findings:
- The issue occurs when I provide a `provider` directly in the `ComponentResourceOptions` while creating a `helm.v3.Chart`.
- Removing the provider injection and using the kubernetes default provider's context to `up` on the same cluster doesn't result in a helm template error.

**Comment by bitofsky** [comment]
Further Update on My Case:
- I've identified the root cause in my scenario.
- The issue appears to be with the kubernetes config information in the `provider`. When it fails to connect to the actual kubernetes cluster, instead of a cluster connection failure, this erroneous version message (v1.20) is displayed.
- After correcting the cluster information, the error no longer occurs.
- The error message seems to be misleading.

**Comment by rhuanbarreto** [comment]
It happens the same to me. But if I switch version back to 4.3.0 it works normally.

**Comment by rhuanbarreto** [comment]
My helm release:
```ts
export const certManager = new k8s.helm.v3.Release("cert-manager", {
  chart: "cert-manager",
  version: "v1.12.2",
  repositoryOpts: {
    repo: "https://charts.jetstack.io",
  },
  name: "cert-manager",
  createNamespace: true,
  namespace: "cert-manager",
  values: {
    installCRDs: true,
  },
});
```

**Comment by mikhailshilkov** [comment]
@EronWright This sounds like a regression, could you please take a look?

**Comment by dominikzogg** [comment]
```
  kubernetes:helm.sh/v3:Release (helm-cert-manager):
    error: kubernetes:helm.sh/v3:Release resource 'helm-cert-manager': property chart value {cert-manager} has a problem: chart requires kubeVersion: >= 1.22.0-0 which is incompatible with Kubernetes v1.20.0; check the chart name and repository configuration.
```

```
new k8s.helm.v3.Release(
    'helm-cert-manager',
    {
      chart: 'cert-manager',
      version: '1.13.2',
      repositoryOpts: {
        repo: 'https://charts.jetstack.io',
      },
      namespace: 'cert-manager',
      createNamespace: true,
      values: {
        installCRDs: true,
        prometheus: {
          enabled: false,
        },
      },
    },
    { provider: k8sProvider },
  );
  ```

**Comment by bhavitsharma** [comment]
yeah, bitten by this bug - can confirm 4.3.0 works

**Comment by rhuanbarreto** [comment]
v4.4.0 still works.

Tested until v4.5.3 . Not working yet.

**Comment by omidraha** [comment]
I have same issue, https://github.com/longhorn/longhorn/issues/4788#issuecomment-1792937587
I fixed the version `pulumi-kubernetes==4.3.0` but how about other packages ?

The `pip` can't  determine which version is compatible with other requirements.

The `requirements.txt` file:
```
pulumi
pulumi-aws
pulumi-aws-native
pulumi-awsx
pulumi-cloudflare
pulumi-docker
pulumi-eks
pulumi-kubernetes==4.3.0
```

**Comment by mikhailshilkov** [comment]
I'm sorry for the trouble everyone - we are working on a fix in https://github.com/pulumi/pulumi-kubernetes/pull/2653 and will land it soon, then cut a new version of the provider.

**Comment by EronWright** [comment]
Update: the fix was shipped in v4.5.4.

**Comment by johnsonp57** [comment]
@EronWright  I am still getting the kubeVersion error post v4.5.4 on deployment of cert-manager - noticed that the JsonNames (lines 400/402) are transposed here:
https://github.com/pulumi/pulumi-kubernetes/blob/master/provider/pkg/gen/dotnet-templates/helm/v3/Chart.cs

**Comment by EronWright** [comment]
@johnsonp57 thanks for the help, I filed an issue based on your observation and will prioritize:
https://github.com/pulumi/pulumi-kubernetes/issues/2739
